name: build
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - run: npm install
      # Запускаем линтер
      - run: npm run lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run setup
        run: make setup # name и run относятся к одной задаче, поэтому дефис ставится только перед name
      - name: run tests
        run: make test
      - name: run lint
        run: make lint
      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
